services:
  appu-dlp:
    image: ghcr.io/nmhappu/appu-dlp:${TAG:-sha-07295f3}
    container_name: appu-dlp-downloader
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
